### ISSUE TITLE
[Feature] Cache management

### ISSUE THREAD

**Issue by Peekmo** [LuvaaX/LuvaaX-CMS#4]
Allow to clear the cache from the back office. The button will start the command `cache:clear`. The `warmup` option and `--env` will be added automatically by reading the `kernel.env` value.

**Comment by ValentinMerlet** [comment]
Seems that we can't call cache:clear command outside the PHP CLI scope. Any better ideas than copy/pasting the execute function of Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand.php ?

**Comment by Peekmo** [comment]
Use the custom service `luvaax.core.command_creator` like used in the entity generator [see here](https://github.com/LuvaaX/LuvaaX-CMS/commit/2c93033ac27f89b8e1aacece6a6e5a7a6b2d4d78#diff-eaa718661706f29d688b68b272b94d02R215)

**Comment by Peekmo** [comment]
Perhaps it could be a good thing to add `--no-debug` in prod environment, and to play the `cache:warmup` in production too ?

**Comment by ValentinMerlet** [comment]
Yep, i'll work on it
